version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./devops/php
            dockerfile: Dockerfile
        image: laravel
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel

    db:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./devops/mysql/init:/docker-entrypoint-initdb.d
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./devops/nginx:/etc/nginx/conf.d/
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - laravel

networks:
    laravel:

volumes:
    mysql_data:
